[package]
name = "zb"
version = "0.1.0"
edition = "2024"
license = "AGPL-3"

[dependencies]
clap = { version = "4.5.20", default-features = false, features = ["derive", "std", "help", "usage", "color", "error-context"] }
nix = { version = "0.30.1", features = ["process", "ptrace", "signal", "feature"] }
chrono = "0.4.41"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
